#!/bin/sh

if [ $# != 1 ]; then
    # need at least one search argument
    echo "Usage: searchpdfs <search-term>"
    exit 1
fi

searchterm=$1
export searchterm
find -L . -name "*.pdf" -print0 | xargs -P 10 -0 -I{} bash -c 'pdftotext -q {} - | grep --color --label={} -H ${searchterm}'

